#!/usr/bin/env python3
"""Generate deserialization tests from the spec's response examples.

Every ``application/json`` response example in the vendored OpenAPI spec is
evidence of a body the API is documented to produce. This script emits one
integration test per example asserting that the corresponding generated
model still deserializes it, and writes them to
``tests/generated_spec_examples.rs`` as a committed, self-contained file
(the example bodies are inlined, so the published crate's tests do not
depend on the spec file, which is excluded from the package).

Target model resolution treats the generated code as the source of truth:

- a success (2xx) example maps to the return type of the generated
  function for its operation, read from the ``Result<models::X, _>``
  signatures in ``src/apis`` — this survives both the generator's
  abbreviation casing and its deduplication of identical inline schemas
  (several operations can share one response model);
- an error example maps to a ``$ref``'d component model or to the
  ``{OperationId}{Status}Response`` inline-schema convention, validated
  against the exports of ``src/models/mod.rs``, and is skipped with a
  notice when neither resolves (error shapes are aggressively deduplicated
  and carry little unique structure).

A success example whose operation cannot be found in ``src/apis`` is a
real drift signal: it is listed on stderr and the script exits with
status 1 so a regeneration cannot quietly lose coverage.

The vendor's examples are not always consistent with the vendor's own
schemas (naive datetimes in ``date-time`` fields, omitted required
fields). After emitting the file the script therefore runs the new tests
once and quarantines every failing one with ``#[ignore]`` and the reason,
so CI stays green while each mismatch stays visible in the committed file
— and disappears from the quarantine automatically once the spec (or the
normalizer) fixes it.

Usage:

    python3 openapi/generate_example_tests.py

Run it after regenerating ``src/apis``/``src/models`` and follow with
``cargo +nightly fmt`` so the emitted file matches the repository style.
"""

from __future__ import annotations

import json
import re
import subprocess
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
SPEC = REPO_ROOT / "openapi" / "timeweb-cloud.json"
APIS_DIR = REPO_ROOT / "src" / "apis"
MODELS_MOD = REPO_ROOT / "src" / "models" / "mod.rs"
OUTPUT = REPO_ROOT / "tests" / "generated_spec_examples.rs"

FUNCTION_RE = re.compile(r"pub async fn (\w+)")
RETURN_RE = re.compile(r"->\s*Result<\s*models::(\w+)")

HTTP_METHODS = ("get", "post", "put", "patch", "delete", "head", "options", "trace")

HEADER = '''\
//! Deserialization tests generated from the OpenAPI response examples.
//!
//! Generated by `openapi/generate_example_tests.py` — do not edit by hand;
//! regenerate after every spec update. Each test parses a response example
//! embedded in the vendored spec into the model the generator produced for
//! that response, pinning the spec, the normalizer and the generator
//! together: if a regeneration breaks deserialization of a documented
//! body, the update fails here instead of in production.
//!
//! Tests marked `#[ignore]` are quarantined: their example does not
//! deserialize because the vendor's example contradicts the vendor's own
//! schema (or the generated model). The quarantine is recomputed on every
//! regeneration, so a fixed example rejoins the active set automatically.

#![allow(clippy::needless_raw_string_hashes, clippy::doc_markdown)]
'''

QUARANTINE_REASON = (
    "quarantined by generate_example_tests.py: "
    "the spec's example does not deserialize into the generated model"
)


def pascal(identifier: str) -> str:
    """Convert an operationId or schema name to the generator's type name."""
    words = re.split(r"[^0-9A-Za-z]+", identifier)
    parts: list[str] = []
    for word in words:
        if not word:
            continue
        chunks = re.findall(r"[A-Z]+(?![a-z])|[A-Z][a-z0-9]*|[a-z0-9]+", word)
        parts.extend(chunk.capitalize() for chunk in chunks)
    return "".join(parts)


def snake(identifier: str) -> str:
    """Convert a type or operation name to a snake_case test identifier."""
    return re.sub(r"(?<=[a-z0-9])(?=[A-Z])", "_", pascal(identifier)).lower()


def normalize(identifier: str) -> str:
    """Case- and separator-insensitive key for matching operation names."""
    return re.sub(r"[^0-9a-z]", "", identifier.lower())


def operation_return_models() -> dict[str, str]:
    """Map normalized operation names to their generated return model."""
    mapping: dict[str, str] = {}
    for source in APIS_DIR.glob("*_api.rs"):
        text = source.read_text()
        functions = list(FUNCTION_RE.finditer(text))
        for current, following in zip(functions, functions[1:] + [None]):
            body_end = following.start() if following else len(text)
            returned = RETURN_RE.search(text, current.end(), body_end)
            if returned:
                mapping[normalize(current.group(1))] = returned.group(1)
    if not mapping:
        raise SystemExit(f"no generated operation signatures found under {APIS_DIR}")
    return mapping


def exported_models() -> set[str]:
    """Collect every model type re-exported from ``src/models/mod.rs``."""
    exports = re.findall(
        r"pub use self::[A-Za-z0-9_]+::([A-Za-z0-9_]+);", MODELS_MOD.read_text()
    )
    if not exports:
        raise SystemExit(f"no model exports found in {MODELS_MOD}")
    return set(exports)


def response_examples(spec: dict) -> list[tuple[str, str, str, str, str, object, dict]]:
    """Yield (operation_id, variant, method, path, status, example, schema)."""
    found = []
    for path, methods in sorted(spec["paths"].items()):
        for method in HTTP_METHODS:
            operation = methods.get(method)
            if not operation:
                continue
            operation_id = operation.get("operationId")
            if not operation_id:
                continue
            for status, response in sorted((operation.get("responses") or {}).items()):
                content = (response.get("content") or {}).get("application/json") or {}
                schema = content.get("schema") or {}
                single = content.get("example", schema.get("example"))
                if single is not None:
                    found.append((operation_id, "", method, path, status, single, schema))
                for name, named in sorted((content.get("examples") or {}).items()):
                    if isinstance(named, dict) and "value" in named:
                        found.append(
                            (operation_id, name, method, path, status, named["value"], schema)
                        )
    return found


def error_model(operation_id: str, status: str, schema: dict) -> str:
    """Name the model an error response maps to when no signature applies."""
    ref = schema.get("$ref", "")
    if ref:
        return pascal(ref.rsplit("/", 1)[-1])
    return f"{pascal(operation_id)}{status}Response"


def render_test(name: str, model: str, example: object, provenance: str) -> str:
    body = json.dumps(example, indent=2, ensure_ascii=False)
    return (
        f"#[test]\n"
        f"fn {name}() {{\n"
        f'    let body = r##"\n{body}\n"##;\n'
        f"    let _: timeweb_rs::models::{model} = serde_json::from_str(body)\n"
        f'        .expect("spec example for {provenance} must deserialize");\n'
        f"}}\n"
    )


def run_tests() -> set[str]:
    """Run the freshly generated tests and return the failing test names."""
    completed = subprocess.run(
        ["cargo", "test", "--test", "generated_spec_examples"],
        cwd=REPO_ROOT,
        capture_output=True,
        text=True,
    )
    failing = set(re.findall(r"^test (\w+) \.\.\. FAILED$", completed.stdout, re.MULTILINE))
    if completed.returncode != 0 and not failing:
        print(completed.stdout, file=sys.stderr)
        print(completed.stderr, file=sys.stderr)
        raise SystemExit("generated tests failed to build")
    return failing


def main() -> int:
    spec = json.loads(SPEC.read_text())
    models = exported_models()
    returns = operation_return_models()

    tests: list[str] = []
    seen: set[str] = set()
    unresolved: list[str] = []
    skipped: list[str] = []

    for operation_id, variant, method, path, status, example, schema in response_examples(spec):
        provenance = f"{method.upper()} {path} {status}" + (f" ({variant})" if variant else "")
        if status.startswith("2"):
            model = returns.get(normalize(operation_id))
            if model is None:
                unresolved.append(f"{provenance}: no generated operation for {operation_id}")
                continue
        else:
            model = error_model(operation_id, status, schema)
            if model not in models:
                skipped.append(f"{provenance}: no model named {model}")
                continue
        suffix = f"_{snake(variant)}" if variant else ""
        name = f"{snake(operation_id)}_{status}{suffix}_example_deserializes"
        while name in seen:
            name += "_more"
        seen.add(name)
        tests.append(render_test(name, model, example, provenance))

    for line in skipped:
        print(f"skipping error example — {line}", file=sys.stderr)
    if unresolved:
        print("success examples without a generated operation:", file=sys.stderr)
        for line in unresolved:
            print(f"  {line}", file=sys.stderr)
        return 1

    OUTPUT.write_text(HEADER + "\n" + "\n".join(tests))
    failing = run_tests()
    if failing:
        text = OUTPUT.read_text()
        for name in failing:
            text = text.replace(
                f"#[test]\nfn {name}(",
                f'#[test]\n#[ignore = "{QUARANTINE_REASON}"]\nfn {name}(',
            )
        OUTPUT.write_text(text)
        print(f"quarantined {len(failing)} tests whose example does not deserialize:")
        for name in sorted(failing):
            print(f"  {name}")
    print(
        f"wrote {len(tests)} tests to {OUTPUT.relative_to(REPO_ROOT)} "
        f"({len(tests) - len(failing)} active, {len(failing)} quarantined)"
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
